apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/anilnokia/hello-world.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
