apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello1
spec:
  selector:
    matchLabels:
      app: hello1
  replicas: 2
  template:
    metadata:
      labels:
        app: hello1
    spec:
      containers:
      - name: hello1
        image: nginxdemos/hello
        ports:
        - containerPort: 80
